CREATE TABLE IF NOT EXISTS `#__mollie_entities` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` varchar(127) NOT NULL,
  `data` MEDIUMTEXT NOT NULL,
  `index1` varchar(255) DEFAULT NULL,
  `index2` varchar(255) DEFAULT NULL,
  `index3` varchar(255) DEFAULT NULL,
  `index4` varchar(255) DEFAULT NULL,
  `index5` varchar(255) DEFAULT NULL,
  `index6` varchar(255) DEFAULT NULL,
  `index7` varchar(255) DEFAULT NULL,
  `index8` varchar(255) DEFAULT NULL,
  `index9` varchar(255) DEFAULT NULL,
  `index10` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_type` (`type`),
  KEY `idx_index1` (`index1`),
  KEY `idx_index2` (`index2`),
  KEY `idx_index3` (`index3`),
  KEY `idx_index4` (`index4`),
  KEY `idx_index5` (`index5`),
  KEY `idx_index6` (`index6`),
  KEY `idx_index7` (`index7`),
  KEY `idx_index8` (`index8`),
  KEY `idx_index9` (`index9`),
  KEY `idx_index10` (`index10`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
